config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :index, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_one_attached :image

    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

    def get_image
        unless image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        image
    end

    def favorite_by?(user)
        favorites.exists?(user_id: user.id)
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book

    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
    validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { maximum: 20, minimum: 2 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top, :about]
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        user_path(current_user.id)
    end

    def after_sign_out_path_for(resource)
        root_path
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    def create
        book = Book.find(params[:book_id])
        comment = current_user.book_comments.new(book_comment_params)
        comment.book_id = book.id
        comment.save
        redirect_to book_path(book)
    end

    def destroy
        book = Book.find(params[:book_id])
        BookComment.find(params[:id]).destroy
        redirect_to book_path(book)
    end

    private

    def book_comment_params
        params.require(:book_comment).permit(:comment)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:image, :title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        redirect_back(fallback_location: root_path)
    end

    def destroy
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path
    else
      render :edit
    end
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if book.errors.any? %>
    <%= book.errors.count %> errors prohibited this obj from being saved:
    <ul>
        <% book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/books/_list.html.erb
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover">
    <tr>
        <th class="header table-link"></th>
        <th class="header table-title">Title</th>
        <th class="header table-body">Opinion</th>
        <th></th>
        <th></th>
    </tr>
    <% @books.each do |book| %>
        <tr>
            <td>
                <%= link_to user_path(book.user_id) do %>
                    <%= image_tag book.get_image %>
                <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id)%></td>
            <td><%= book.body %></td>
            <td>
            <% if  book.favorite_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fa-solid fa-heart"></i><%= link_to book.favorites.count %>
                <% end %>
            <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fa-regular fa-heart"></i><%= link_to book.favorites.count %>
                <% end %>
            <% end %>
            </td>
            <td>コメント数:<%= book.book_comments.count %></td>
        </tr>

    <% end %>
</table>
<div>

app/views/books/edit.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div>
            <h2>Editing Book</h2>
            <%= render 'books/error', book:@book %>
            <%= form_with model: @book do |f| %>
                <%= f.label :title %><br>
                <%= f.text_field :title %>
                <br>
                <%= f.label :body %><br>
                <%= f.text_area :body %>
                <br>
                <%= f.submit 'Update Book' %>
                <br>
                <span><%= link_to 'Show', book_path(@book.id) %></span>
                <span><%= link_to 'Back', books_path %></span>
            <% end %>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<% if not @book.nil? %>
    <%= render 'books/error', book:@book %>
<% end %>
<div class="container">
    <div class="row">
        <%= render'users/list', user:current_user %>
        <%= render 'books/list', books:@books %>
    </div>
</div>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @book do |f| %>
  <h4>ショップ名</h4>
  <%= f.text_field :title %>
  <h4>説明</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<% if not flash[:notice] == nil %>
    <div class="flash-message">
    <%= flash[:notice] %>
    </div>
<% end %>
<div class="container">
    <div class="row">
        <%= render'users/list', user:@book.user %>
        <div class="col-md-8 offset-md-1">
            <h2>Book detail</h2>
            <table class="table">
                <tr>
                    <td><%= image_tag @book.get_image %></td>
                    <td><%= link_to @book.title, book_path(@book.id) %></td>
                    <td><%= @book.body %></td>
                    <td>
                        <% if  @book.favorite_by?(current_user) %>
                            <%= link_to book_favorites_path(@book), method: :delete do %>
                                <i class="fa-solid fa-heart"></i><%= link_to @book.favorites.count %>
                            <% end %>
                        <% else %>
                            <%= link_to book_favorites_path(@book), method: :post do %>
                                <i class="fa-regular fa-heart"></i><%= link_to @book.favorites.count %>
                            <% end %>
                        <% end %>
                    </td>
                    <td>コメント数:<%= @book.book_comments.count %></td>
                    <% if @book.user == current_user %>
                        <td><button type="button" class="btn btn-success"><%= link_to 'Edit', edit_book_path(@book), class: "text-light" %></button></td>
                        <td><button type="button" class="btn btn-danger"><%= link_to 'Destroy', book_path(@book), method: :delete, class: "text-light" %></button></td>
                    <% end %>
                </tr>
            </table>
            <div><%= link_to @book.user.name, user_path(@book.user.id) %></div>
            <div>
                <% @book.book_comments.each do |comment| %>
                    <span>
                        <%= link_to user_path(comment.user.id) do %>
                            <%= image_tag comment.user.get_profile_image(100,100) %>
                        <% end %>
                    </span>
                    <span>
                       <%= comment.comment %> 
                    </span>
                    <% if comment.user == current_user %>
                        <span>
                            <button type="button" class="btn btn-danger"><%= link_to 'Destroy', book_book_comment_path(comment.book, comment), method: :delete, class: "text-light" %></button>
                        </span>
                    <% end %>
                    <div>
                        <%= link_to comment.user.name , user_path(comment.user.id) %>
                    </div>        
                <% end %>
            </div>
            <div>
                <%= form_with model: [@book, @book_comment] do |f| %>
                    <%= f.text_area :comment, class: "form-control" %>
                    <%= f.submit "送信", class: "btn btn-primary" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/homes/about.html.erb
<h2 class="text-center">welcome to <i class="fas fa-book"></i>Bookers !!</h2>
<br>
<p class="text-center">CopyRight Infratop.inc</p>

app/views/homes/top.html.erb
<% if not flash[:notice] == nil %>
    <div class="flash-message">
    <%= flash[:notice] %>
    </div>
<% end %>
<div class="container-fluid">
    <div class="row justify-content-center">
        <div>
            <h2>welcome to <i class="fa-solid fa-book"></i>Bookers !!</h2>
            <p>
                In <i class="fas fa-book"></i>Bookers,<br>
                you can share and excange your opinions, impressions, and emotions<br>
                about various books!
            </p>
            <div class="row justify-content-center">
                <button type="button" class="btn btn-primary">
                    <%= link_to 'Log in',  new_user_session_path, class: "text-light" %>
                </button>
            </div>
            <div class="row justify-content-center">
                <button type="button" class="btn btn-success">
                    <%= link_to 'Sign up',  new_user_session_path, class: "text-light" %>
                </button>
            </div>
            <br>
            <p class="text-center">CopyRight Infratop.inc</p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/35c57b14e8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="f-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <span class="navbar-brand p-3"><%= link_to 'Bookers', root_path, class: 'nav-link text-light' %></span>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id) do %>
                  <i class="fas fa-home nav-link text-light">Home</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path do %>
                  <i class="fas fa-users nav-link text-light">Users</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path do %>
                  <i class="fas fa-book-open nav-link text-light">Books</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt nav-link text-light">Log out</i>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path do %>
                  <i class="fas fa-home nav-link text-light">Home</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path do %>
                  <i class="fas fa-link nav-link text-light">About</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path do %>
                  <i class="fas fa-user-plus nav-link text-light">Sign up</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path do %>
                  <i class="fas fa-sign-in-alt nav-link text-light">Log in</i>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/_list.html.erb
<% if user_signed_in? %>
  <div class="sidebar col-md-3">
    <div class="user">
      <h2>User info</h2>
      <%= image_tag  user.get_profile_image(100,100) %>
      <table class="table">
        <tr>
          <th>name</th>
          <td><%= user.name %></td>
        </tr>
        <tr>
          <th>introduction</th>
          <td><%= user.introduction %></td>
        </tr>
      </table>
      <% if user == current_user %>
        <button type="button" class="btn btn-outline-secondary btn-block">
          <%= link_to edit_user_path(user.id) do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </button>
      <% else %>
        <button type="button" class="btn btn-outline-secondary btn-block">
          <%= link_to edit_user_path(user.id) do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </button>
      <% end %>
    </div>
    <div class="post">
      <%= form_with model: Book.new,  url:books_path, mehtod: :post do |f| %>
        <h4>New book</h4>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
        <br>
        <%= f.label :body, 'Opinion' %><br>
        <%= f.text_field :body %>
        <br>
        <%= f.submit 'Create Book', class: 'bg-success text-light' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div>
            <h2>User info</h2>
            <%= render 'books/error', book:@user %>
            <%= form_with model: @user do |f| %>
                <%= f.label :name %><br>
                <%= f.text_field :name %>
                <br>
                <%= f.label :profile_image, 'Image' %><br>
                <%= f.file_field :profile_image %>
                <br>
                <%= f.label :introduction %><br>
                <%= f.text_area :introduction %>
                <br>
                <%= f.submit 'Update User' %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
        <%= render'users/list', user:current_user %>
        <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-hover">
            <tr>
                <th class="header table-link">image</th>
                <th class="header table-title">name</th>
                <th class="header table-body"></th>
            </tr>
            <% @users.each do |user| %>
                <tr>
                    <td><%= image_tag user.get_profile_image(100,100) %></td>
                    <td><%= user.name %></td>
                    <td><%= link_to 'Show', user_path(user.id) %></td>
                </tr>
            <% end %>
        </table>
        <div>
    </div>
</div>

app/views/users/show.html.erb
<% if not flash[:notice] == nil %>
    <div class="flash-message">
    <%= flash[:notice] %>
    </div>
<% end %>
<div class="container">
    <div class="row">
        <%= render'users/list', user:@user %> 
        <%= render 'books/list', books:@books %>
    </div>
</div>